# Generated by Django 2.2.3 on 2019-07-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('north', models.IntegerField(default=0)),
                ('south', models.IntegerField(default=0)),
                ('east', models.IntegerField(default=0)),
                ('west', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('health_points', models.FloatField()),
                ('lives', models.IntegerField(default=3)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Room')),
            ],
        ),
    ]
