# Generated by Django 2.2.3 on 2019-08-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
        ),
        migrations.RemoveField(
            model_name='room',
        ),
    ]
