# Generated by Django 2.2.3 on 2019-08-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_auto_20190801_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='toys',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='room_id',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='Toys',
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
