# Generated by Django 2.2.3 on 2019-08-01 19:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_auto_20190801_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default='none', size=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
