# Generated by Django 2.2.3 on 2019-08-01 17:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20190730_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
