# Generated by Django 2.2.3 on 2019-08-01 17:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20190801_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
